### ISSUE TITLE
Security Error when going to https://zacookiegames.com

### ISSUE THREAD

**Issue by idvorkin** [zacookiegames/zacookiegames.github.io#6]
When going to https://zacookiegames.com we got a security error from some kind of redirector. The issue is now no repro. 

I’ll try to capture more information next time it happens.

**Comment by idvorkin** [comment]
Closing Issue as No Repro

**Comment by idvorkin** [comment]
Got another instance. Sounds like its this issue: 
https://www.godaddy.com/community/SSL-And-Security/Connection-is-not-private-but-website-have-ssl-certificate/td-p/138237?sc_code=1

The invalid certificate was: 

```
Your connection is not private
Attackers might be trying to steal your information from zacookiegames.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: shortener.secureserver.net

Issuer: Starfield Secure Certificate Authority - G2

Expires on: Sep 26, 2020

Current date: Mar 4, 2020
```

**Comment by idvorkin** [comment]
I erased the domain forwarding (in theory from zacookiegames.com to www.zacookiegames.com) which I think fixes it. Holler if you find this again.

**Comment by zmdvorkin** [comment]
Issue has not been resolved, dont know whats causing it

**Comment by zmdvorkin** [comment]
Turns out DNS was misconfigured. DNS should have been 3 digit 110, 111, 108, 109. However, accidently configured as 11. 

```
;; ANSWER SECTION:
zacookiegames.com.      300     IN      A       185.199.110.153
zacookiegames.com.      300     IN      A       185.199.11.153
zacookiegames.com.      300     IN      A       185.199.108.153
zacookiegames.com.      300     IN      A       185.199.109.153
```

Now fixed: 

```

;; ANSWER SECTION:
zacookiegames.com.      300     IN      A       185.199.110.153
zacookiegames.com.      300     IN      A       185.199.11.153
zacookiegames.com.      300     IN      A       185.199.108.153
zacookiegames.com.      300     IN      A       185.199.109.153
```

**Comment by zmdvorkin** [comment]
Short write up here: https://idvork.in/cert-error
